name: PlatformIO CI

on: [push]

jobs:
  build-base:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build Base Station
        run: pio run -e base
      - uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: .pio/build/base/firmware.bin
          include-hidden-files: true
  build-vehicles:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build Dump
        run: pio run -e dump

      - uses: actions/upload-artifact@v4
        with:
          name: dump-firmware
          path: .pio/build/dump/firmware.bin
          include-hidden-files: true
